Step1/sjy - 구현
Java-Bom/cafe pull request #5
Opened 2020-07-18 14:21 UTC by csbsjy

![image](https://user-images.githubusercontent.com/47847993/87854484-54c3bc00-c94d-11ea-96f4-b1690662a5bd.png)

2020-07-20 05:45 UTC, pci2676 requested changes
테스트 코드가 너무 없넹...!!
요구사항 구현이 잘못 되어있는 부분이 있어서 Approve하지 않을게!

2020-07-20 05:45 UTC, pci2676 commented on README.md
> +- 한 테이블에 주문 할 수 있는 한 메뉴의 수량은 최대 30개이다. - o
이 부분 요구사항 구현이 잘못 되어 있네 ㅎㅎ
메뉴 A를 30개 주문하고 B를 주문하면 exception이 발생하네!

2020-07-20 05:45 UTC, pci2676 commented on README.md
> +- 한 테이블에 주문 할 수 있는 한 메뉴의 수량은 최대 30개이다. - o
`- 프로그램은 종료를 입력하기 전까지 종료되어서는 안된다.`
이 부분도 지켜지지 않았네! ㅎㅎㅎ

2020-07-20 05:45 UTC, pci2676 commented on src/main/java/cafe/service/CafeService.java
> +    }
위 로직은 Service의 책임이라는 생각이 들지 않아!

2020-07-20 05:45 UTC, pci2676 commented on src/main/java/cafe/service/CafeService.java
> +    }
비슷하게 Service에 너무 많은 로직이 구현되어 있는것 같아!

2020-07-22 14:54 UTC, csbsjy commented on src/main/java/cafe/service/CafeService.java
> +    }
헉 그런가요!? 잘 공감이안가용! 저는 클라이언트 관심사를 기준으로 요구사항을 뽑았을 때(InputView 기준)
- 주문하기
- 주문내역확인하기
- 총 금액 계산하기

라고 뽑았고 그걸 Service 에 담은거거든용. Service 책임이 아니라고 생각하시는데에 대한 의견이 궁금합니다요

2020-08-01 11:45 UTC, pci2676 commented on src/main/java/cafe/service/CafeService.java
> +    }
서비스가 
- 주문하기
- 주문내역확인하기
- 총 금액 계산하기

의 기능을 인터페이스로 가지고 있는건 맞다고 생각해!

리뷰한지가 너무 오래되서 다시 코드를 봤는데 `Service`에 너무 내부 구현의 노출이 많이 되어 있다는 느낌을 받아서 저렇게 리뷰를 했던 것 같아!
`List<Order>`에서 특정 메뉴만을 가져오는 것은 `Orders`라는 일급컬렉션을 만들어서 처리하는 방식으로 내부 구현을 다른 객체에게 위임했으면 해서 했던 리뷰였던것 같아!

2021-03-19 06:02 UTC, merged